import {IStationNames} from "../../interfaces/IStationNames";

const colors = {
    green: "#1EAD35",
    blue: "#4757E2",
    red: "#ec2222",
    orange: "#FF9519",
    purple: "#8a40ad"
}

const metroStationsListSPB: IStationNames = {
    "Беговая": colors.green,
    "Зенит": colors.green,
    "Приморская": colors.green,
    "Василеостровская": colors.green,
    "Невский проспект": colors.blue,
    "Гостиный двор": colors.green,
    "Маяковская": colors.green,
    "Площадь Восстания": colors.red,
    "Площадь Александра Невского 1": colors.green,
    "Площадь Александра Невского 2": colors.orange,
    "Елизаровская": colors.green,
    "Ломоносовская": colors.green,
    "Пролетарская": colors.green,
    "Обухово": colors.green,
    "Рыбацкое": colors.green,
    "Комендантский проспект": colors.purple,
    "Старая Деревня": colors.purple,
    "Крестовский остров": colors.purple,
    "Чкаловская": colors.purple,
    "Спортивная": colors.purple,
    "Адмиралтейская": colors.purple,
    "Пушкинская": colors.red,
    "Звенигородская": colors.purple,
    "Обводный канал": colors.purple,
    "Волковская": colors.purple,
    "Бухарестская": colors.purple,
    "Международная": colors.purple,
    "Проспект Славы": colors.purple,
    "Дунайская": colors.purple,
    "Шушары": colors.purple,
    "Парнас": colors.blue,
    "Проспект Просвещения": colors.blue,
    "Озерки": colors.blue,
    "Удельная": colors.blue,
    "Пионерская": colors.blue,
    "Чёрная речка": colors.blue,
    "Петроградская": colors.blue,
    "Горьковская": colors.blue,
    "Технологический институт 1": colors.red,
    "Технологический институт 2": colors.blue,
    "Фрунзенская": colors.blue,
    "Московские ворота": colors.blue,
    "Электросила": colors.blue,
    "Парк Победы": colors.blue,
    "Московская": colors.blue,
    "Звёздная": colors.blue,
    "Купчино": colors.blue,
    "Девяткино": colors.red,
    "Гражданский проспект": colors.red,
    "Академическая": colors.red,
    "Политехническая": colors.red,
    "Площадь Мужества": colors.red,
    "Лесная": colors.red,
    "Выборгская": colors.red,
    "Площадь Ленина": colors.red,
    "Чернышевская": colors.red,
    "Достоевская": colors.orange,
    "Владимирская": colors.red,
    "Балтийская": colors.red,
    "Нарвская": colors.red,
    "Кировский завод": colors.red,
    "Автово": colors.red,
    "Ленинский проспект": colors.red,
    "Проспект Ветеранов": colors.red,
    "Лиговский проспект": colors.orange,
    "Новочеркасская": colors.orange,
    "Ладожская": colors.orange,
    "Проспект Большевиков": colors.orange,
    "Улица Дыбенко": colors.orange,
    "Садовая": colors.purple,
    "Сенная площадь": colors.blue,
    "Спасская": colors.orange
};

export default metroStationsListSPB;